name: Build documentation

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    name: Build HTML documentation
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install ALSA headers
        run: sudo apt-get install libasound2-dev

      - name: Build HTML documentation
        run: make -C doc html

      - name: Upload HTML documentation
        uses: actions/upload-artifact@v7
        with:
          name: documentation-html
          path: doc/html
          if-no-files-found: error
